FROM python:3.12-slim AS base

COPY --from=ghcr.io/astral-sh/uv:0.9.9 /uv /uvx /usr/local/bin/

WORKDIR /app

# COPY pyproject.toml uv.lock ./
# RUN uv sync --frozen --no-install-project --no-dev

COPY docker/requirements-ui.txt .
RUN uv pip install --system -r requirements-ui.txt

COPY ui ./ui

ENV PYTHONUNBUFFERED=1 \
    PATH="/app/.venv/bin:$PATH"

EXPOSE 8501

CMD ["streamlit", "run", "ui/app.py", "--server.address=0.0.0.0", "--server.port=8501"]