apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      - job_name: credit_bureau
        static_configs:
          - targets: ["mcp-servers:8001"]

      - job_name: bank_statement_parser
        static_configs:
          - targets: ["mcp-servers:8002"]

      - job_name: policy_rules_engine
        static_configs:
          - targets: ["mcp-servers:8003"]